name: my_first_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10
  sqflite: ^2.3.2
  path: ^1.8.3
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sem_imagem.png
    - assets/images/pokeball.svg
  fonts: 
    - family: MonoSans
      fonts:
        - asset: assets/fonts/MonaSans/TTF/Mona-Sans-Regular.ttf
        - asset: assets/fonts/MonaSans/TTF/Mona-Sans-Bold.ttf
